services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  # Live code reloading
    ports:
      - "8004:8004"
    environment:
      - DEBUG=1  # Enable Django debug mode
      - DATABASE_URL=postgres://postgres:postgres@db:5432/insurance_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app  # Live code reloading
      # - /app/node_modules  # Preserve installed modules
      - /app/.next
    ports:
      - "3000:3000"  # Nextjs server port
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    env_file:
      - frontend/.env
    networks:
      - app-network
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"
  
  db:
    image: postgres:17.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: